### ISSUE TITLE
Remove use of old AutoDoc constructs

### ISSUE THREAD

**Issue by fingolfin** [homalg-project/AlgebraicThomas#6]
This is one of only two remaining packages which still uses the old AutoDoc APIs such as `DeclareOperationWithDocumentation` and `DeclareAttributeWithDocumentation`.

It would be nice if this package could be migrated to the new way of writing AutoDoc code. That would get us one step closer to removing the code implementing it in AutoDoc.

See gap-packages/AutoDoc#94

**Comment by mohamed-barakat** [comment]
Go ahead and remove it. This will force us to update.

**Comment by sebasguts** [comment]
Please have a look at #7. I already did the changes

**Comment by mohamed-barakat** [comment]
You forgot to git rm doc/AlgebraicThomas.xml. I deleted it and pushed. Still the commit is broken:

```
# make clean
# make doc
...
Error, Function: number of arguments must be 1 (not 4)
not in any function at line 3 of createautodoc.g
you can replace the argument list <args> via 'return <args>;'
brk>
Reading file "createautodoc.g" has been aborted.
```

**Comment by sebasguts** [comment]
New PullRequest right now. Turns out, the pull request was there all the time :)

**Comment by mohamed-barakat** [comment]
Funktioniert, danke :+1:
